# Generated by Django 4.2.1 on 2023-07-06 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('casa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.ventasap')),
            ],
        ),
    ]
