# Generated by Django 4.2.1 on 2023-07-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comentario', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
