# Generated by Django 4.2.1 on 2023-07-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ventasaptos_alter_visita_casa_delete_ventasap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventasaptos',
            old_name='imagend',
            new_name='imagen_dos',
        ),
        migrations.RenameField(
            model_name='ventasaptos',
            old_name='imagent',
            new_name='imagen_tres',
        ),
    ]
